### ISSUE TITLE
To-Do v1.0

### ISSUE THREAD

**Issue by umaim** [Cloud-Swift/SKE#1]
Features:
- [x] Write tutorial in README.md.
- [x] Add License.
- [x] Eslint support.
- [x] Colorful icon.
- [x] Export keys to csv files with title.
- [x] Responsive design for mobile devices.
- [x] Full PWA.
- [x] Save bot name to local storage.
- [x] i18n.
- [x] Change navbar icon.
- [x] Audits checklist.
- [x] Blackbox Test.
- [x] Check Audits again.
- [x] Add Rassian.
- [x] Add button tooltips.
- [x] Add license info in README
- [x] Add privacy Policy
- [x] Update tutorial.
